server:
  port: 10000
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://name:password@127.0.0.1:7002/eureka
# 解决第一次请求报超时异常的方案：
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
zuul:
  routes: 
    eurekaClient: 
      path: /pxl/** 
      service-id: eurekaClient
  #ignored-headers: 禁止传播某些头信息
  prefix: /app 
  strip-prefix: false  #不可用
logging: 
  level: 
    com.netflix: debug
management:
  security:
    enabled: false
    

  
