server:
  port: 8001
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://name:password@127.0.0.1:7002/eureka
# 解决第一次请求报超时异常的方案：
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

