server:
  port: 8002
spring:
  application:
    name: eurekaClient
eureka:
  client:
    service-url:
      defaultZone: http://name:password@127.0.0.1:7002/eureka,http://name:password@127.0.0.1:7003/eureka