server:
  port: 9011
spring:
  application:
    name: feign
eureka:
  client:
    service-url:
      defaultZone: http://name:password@127.0.0.1:7002/eureka
logging:
  level:
    com.pxl.feign.FeignClient: DEBUG
# 解决第一次请求报超时异常的方案：
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000

